version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: egdc-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # Basic authentication
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=EgdcN8n2024!
      
      # Host configuration
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      
      # Timezone and locale
      - GENERIC_TIMEZONE=America/Bogota
      - N8N_DEFAULT_LOCALE=es
      
      # Database - PostgreSQL for production
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=n8n-postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n_user
      - DB_POSTGRESDB_PASSWORD=N8nSecure2024!
      - DB_POSTGRESDB_SCHEMA=public
      
      # Security
      - N8N_ENCRYPTION_KEY=EgdcN8nEncryptionKey2024Secret
      
      # Workflow settings
      - EXECUTIONS_TIMEOUT=3600
      - EXECUTIONS_TIMEOUT_MAX=7200
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - EXECUTIONS_DATA_MAX_AGE=336
      
      # Performance
      - N8N_PAYLOAD_SIZE_MAX=16
      
      # Features
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_TEMPLATES_ENABLED=true
      - N8N_PUBLIC_API_DISABLED=false
      - N8N_METRICS=true
      - N8N_LOG_LEVEL=info
      - N8N_LOG_OUTPUT=console
      
      # EGDC API connection
      - EGDC_API_URL=http://host.docker.internal:3000/api
      - EGDC_DATABASE_URL=postgresql://egdc_user:EgdcSecure2024!@34.45.148.180:5432/egdc_inventory

    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/workflows:/home/node/.n8n/workflows
      - ./n8n/credentials:/home/node/.n8n/credentials
    
    depends_on:
      - n8n-postgres
    
    networks:
      - egdc-network

  n8n-postgres:
    image: postgres:15
    container_name: egdc-n8n-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n_user
      - POSTGRES_PASSWORD=N8nSecure2024!
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - n8n_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - egdc-network

  # Redis for queue mode (high-performance setup)
  redis:
    image: redis:7-alpine
    container_name: egdc-n8n-redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=RedisSecure2024!
    command: redis-server --requirepass RedisSecure2024!
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - egdc-network

volumes:
  n8n_data:
    driver: local
  n8n_postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  egdc-network:
    driver: bridge